name: GitHub-Profile-3D-Contrib

on:
  schedule: # 00:00 JST == 15:00 UTC
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: hyun071/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          hyun071: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config hyun071 github-actions
          git config rhdclsla@gmail.com github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
